// laravel/v3/frontend/src/app/module/admin/view/security/user/view/user-view-admin.component.ts
import {Component, OnInit} from '@angular/core';


import {AbstractViewController} from 'src/app/zynerator/controller/AbstractViewController';
import { environment } from 'src/environments/environment';

import {UserAdminService} from 'src/app/controller/service/admin/security/UserAdmin.service';
import {UserDto} from 'src/app/controller/model/security/User.model';
import {UserCriteria} from 'src/app/controller/criteria/security/UserCriteria.model';

import {RoleDto} from 'src/app/controller/model/security/Role.model';
import {RoleAdminService} from 'src/app/controller/service/admin/security/RoleAdmin.service';
import {ModelPermissionUserDto} from 'src/app/controller/model/security/ModelPermissionUser.model';
import {ModelPermissionUserAdminService} from 'src/app/controller/service/admin/security/ModelPermissionUserAdmin.service';
import {ModelPermissionDto} from 'src/app/controller/model/security/ModelPermission.model';
import {ModelPermissionAdminService} from 'src/app/controller/service/admin/security/ModelPermissionAdmin.service';
import {RoleUserDto} from 'src/app/controller/model/security/RoleUser.model';
import {RoleUserAdminService} from 'src/app/controller/service/admin/security/RoleUserAdmin.service';
import {ActionPermissionDto} from 'src/app/controller/model/security/ActionPermission.model';
import {ActionPermissionAdminService} from 'src/app/controller/service/admin/security/ActionPermissionAdmin.service';
@Component({
  selector: 'app-user-view-admin',
  templateUrl: './user-view-admin.component.html'
})
export class UserViewAdminComponent extends AbstractViewController<UserDto, UserCriteria, UserAdminService> implements OnInit {

    roleUsers = new RoleUserDto();
    roleUserss: Array<RoleUserDto> = [];
    modelPermissionUsers = new ModelPermissionUserDto();
    modelPermissionUserss: Array<ModelPermissionUserDto> = [];

    constructor(private userService: UserAdminService, private roleService: RoleAdminService, private modelPermissionUserService: ModelPermissionUserAdminService, private modelPermissionService: ModelPermissionAdminService, private roleUserService: RoleUserAdminService, private actionPermissionService: ActionPermissionAdminService){
        super(userService);
    }

    ngOnInit(): void {
    }


    get role(): RoleDto {
       return this.roleService.item;
    }
    set role(value: RoleDto) {
        this.roleService.item = value;
    }
    get roles(): Array<RoleDto> {
       return this.roleService.items;
    }
    set roles(value: Array<RoleDto>) {
        this.roleService.items = value;
    }
    get modelPermission(): ModelPermissionDto {
       return this.modelPermissionService.item;
    }
    set modelPermission(value: ModelPermissionDto) {
        this.modelPermissionService.item = value;
    }
    get modelPermissions(): Array<ModelPermissionDto> {
       return this.modelPermissionService.items;
    }
    set modelPermissions(value: Array<ModelPermissionDto>) {
        this.modelPermissionService.items = value;
    }
    get actionPermission(): ActionPermissionDto {
       return this.actionPermissionService.item;
    }
    set actionPermission(value: ActionPermissionDto) {
        this.actionPermissionService.item = value;
    }
    get actionPermissions(): Array<ActionPermissionDto> {
       return this.actionPermissionService.items;
    }
    set actionPermissions(value: Array<ActionPermissionDto>) {
        this.actionPermissionService.items = value;
    }


}


<p-dialog [(visible)]="viewDialog" [style]="{width: '70vw'}" header="{{'user.tabPan' | translate}}" [modal]="true" styleClass="p-fluid">
    <ng-template pTemplate="content">
        <p-tabView>
            <p-tabPanel header="{{'user.tabPan' | translate}}">
                <div class="grid">
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="1">{{'user.credentialsNonExpired' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="1"  [disabled]="true" [(ngModel)]="item.credentialsNonExpired"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="2">{{'user.enabled' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="2"  [disabled]="true" [(ngModel)]="item.enabled"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="3">{{'user.email' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.email' | translate}}" autofocus  id="3" [(ngModel)]="item.email">
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="4">{{'user.accountNonExpired' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="4"  [disabled]="true" [(ngModel)]="item.accountNonExpired"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="5">{{'user.accountNonLocked' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="5"  [disabled]="true" [(ngModel)]="item.accountNonLocked"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="6">{{'user.username' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.username' | translate}}" autofocus  id="6" [(ngModel)]="item.username">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="7">{{'user.password' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.password' | translate}}" autofocus  id="7" [(ngModel)]="item.password">
                    </div>
                    <div class="field align-inputswitch col-12  md:col-6">
                        <div  class="label-inputswitch">
                            <label for="8">{{'user.passwordChanged' | translate}}</label>
                        </div>
                        <div class="input-switch">
                            <p-inputSwitch id="8"  [disabled]="true" [(ngModel)]="item.passwordChanged"></p-inputSwitch>
                        </div>
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="9">{{'user.lastName' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.lastName' | translate}}" autofocus  id="9" [(ngModel)]="item.lastName">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="10">{{'user.firstName' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.firstName' | translate}}" autofocus  id="10" [(ngModel)]="item.firstName">
                    </div>
                    <div class="field col-12 md:col-6">
                        <label for="11">{{'user.phone' | translate}}</label>
                        <input class="mb-2 mr-2" type="text" pInputText [disabled]="true" placeholder="{{'user.phone' | translate}}" autofocus  id="11" [(ngModel)]="item.phone">
                    </div>
                </div>
            </p-tabPanel>

            <p-tabPanel header="{{'user.modelPermissionUsers' | translate}}">
                <div class="grid">
                    <div class="col">
                        <div class="card">
                            <p-table [value]="item.modelPermissionUsers" [scrollable]="true" scrollHeight="200px">
                                <ng-template pTemplate="header">
                                    <tr>
                                        <th>Value</th>
                                        <th>Sub attribute</th>
                                        <th>Action permission</th>
                                        <th>Model permission</th>
                                    </tr>
                                </ng-template>
                                <ng-template pTemplate="body" let-p>
                                    <tr>
                                        <td><i *ngIf="p.value" class="pi pi-check checked-toogle"></i>
                                            <i *ngIf="!p.value" class="pi pi-times unchecked-toogle"></i>
                                        </td>
                                        <td>{{p.subAttribute}}</td>
                                        <td>{{p.actionPermission?.id}}</td>
                                        <td>{{p.modelPermission?.id}}</td>
                                    </tr>
                                </ng-template>
                            </p-table>
                        </div>
                    </div>
                </div>
            </p-tabPanel>
        </p-tabView>

    </ng-template>

    <ng-template pTemplate="footer" >
        <div class="grid-footer">
            <div>
                <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideViewDialog()"></button>
            </div>
        </div>
    </ng-template>
</p-dialog>

// next/security/user and permission/frontend/components/admin/view/security/user/view/user-view-admin.component.tsx
import {Column} from 'primereact/column';
import {TabPanel, TabView} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {InputTextarea} from 'primereact/inputtextarea';
import React from 'react';
import {Calendar} from 'primereact/calendar';
import {InputSwitch} from 'primereact/inputswitch';
import {TFunction} from "i18next";

import  {UserDto}  from '@/controller/model/security/User.model';

import useViewHook from "@/utils/zyhook/useViewhook";

type UserViewAdminType = {
    visible: boolean,
    onClose: () => void,
    selectedItem: UserDto,
    t: TFunction
}

const View: React.FC<UserViewAdminType> = ({visible,onClose,selectedItem, t}) => {

    const {
    onTabChange,
    hideDialog,
    itemDialogFooter,
    formateDate,
    parse,
    parseToIsoFormat,
    adaptDate,
    activeIndex
    } = useViewHook<UserDto>({selectedItem, onClose})

        return(
<Dialog visible={visible} style={{width: '70vw'}} header={t("user.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
<TabView activeIndex={activeIndex} onTabChange={onTabChange}>
<TabPanel header={t("user.tabPan")}>
    <div className="formgrid grid">

        <div className="field col-6">
            <div  className="label-inputswitch">
                    <label htmlFor="credentialsNonExpired">{t("user.credentialsNonExpired")}</label>
                    <span className="p-float-label">
                        <InputSwitch  id="credentialsNonExpired" checked={selectedItem?.credentialsNonExpired} disabled />
                    </span>
            </div>
            </div>

        <div className="field col-6">
            <div  className="label-inputswitch">
                    <label htmlFor="enabled">{t("user.enabled")}</label>
                    <span className="p-float-label">
                        <InputSwitch  id="enabled" checked={selectedItem?.enabled} disabled />
                    </span>
            </div>
            </div>

            <div className="field col-6">
                <label htmlFor="email">{t("user.email")}</label>
                <InputText id="email" value={selectedItem?.email} disabled   />
            </div>

        <div className="field col-6">
            <div  className="label-inputswitch">
                    <label htmlFor="accountNonExpired">{t("user.accountNonExpired")}</label>
                    <span className="p-float-label">
                        <InputSwitch  id="accountNonExpired" checked={selectedItem?.accountNonExpired} disabled />
                    </span>
            </div>
            </div>

        <div className="field col-6">
            <div  className="label-inputswitch">
                    <label htmlFor="accountNonLocked">{t("user.accountNonLocked")}</label>
                    <span className="p-float-label">
                        <InputSwitch  id="accountNonLocked" checked={selectedItem?.accountNonLocked} disabled />
                    </span>
            </div>
            </div>

            <div className="field col-6">
                <label htmlFor="username">{t("user.username")}</label>
                <InputText id="username" value={selectedItem?.username} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="password">{t("user.password")}</label>
                <InputText id="password" value={selectedItem?.password} disabled   />
            </div>

        <div className="field col-6">
            <div  className="label-inputswitch">
                    <label htmlFor="passwordChanged">{t("user.passwordChanged")}</label>
                    <span className="p-float-label">
                        <InputSwitch  id="passwordChanged" checked={selectedItem?.passwordChanged} disabled />
                    </span>
            </div>
            </div>

            <div className="field col-6">
                <label htmlFor="lastName">{t("user.lastName")}</label>
                <InputText id="lastName" value={selectedItem?.lastName} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="firstName">{t("user.firstName")}</label>
                <InputText id="firstName" value={selectedItem?.firstName} disabled   />
            </div>

            <div className="field col-6">
                <label htmlFor="phone">{t("user.phone")}</label>
                <InputText id="phone" value={selectedItem?.phone} disabled   />
            </div>

        </div>
</TabPanel>
    <TabPanel header={t("user.modelPermissionUsers")}>
                <div className="card">
                    <DataTable value={selectedItem?.modelPermissionUsers} tableStyle={{minWidth: '50rem'}} dataKey="id">
                                <Column field="value" header={t("modelPermissionUser.value")}   ></Column>
                                <Column field="subAttribute" header={t("modelPermissionUser.subAttribute")}   ></Column>
                                <Column field="actionPermission.id" header={t("modelPermissionUser.actionPermission")}></Column>
                                <Column field="modelPermission.id" header={t("modelPermissionUser.modelPermission")}></Column>
                    </DataTable>
                </div>
        </TabPanel>
</TabView>
</Dialog>
);
};
export default View;
