// next/security/frontend/components/admin/view/security/model-permission/edit/model-permission-edit-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar} from 'primereact/calendar';
import { format } from 'date-fns';
import { parse } from 'date-fns';
import { InputSwitch } from 'primereact/inputswitch';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';


import {MessageService} from '@/utils/zynerator/service/MessageService';


import {TFunction} from "i18next";
import {Toast} from "primereact/toast";

import useEditHook from "@/utils/zyhook/useEdit.hook";


import {ModelPermissionAdminService} from '@/controller/service/admin/security/ModelPermissionAdminService.service';
import  {ModelPermissionDto}  from '@/controller/model/security/ModelPermission.model';
import {ModelPermissionCriteria} from "@/controller/criteria/security/ModelPermissionCriteria.model";




type ModelPermissionEditAdminType = {
    visible: boolean,
    onClose: () => void,
    showToast: React.Ref<Toast>,
    selectedItem: ModelPermissionDto
    update: (item: ModelPermissionDto) => void,
    list: ModelPermissionDto[],
    service: ModelPermissionAdminService,
    t: TFunction
}
const Edit: React.FC<ModelPermissionEditAdminType> = ({visible, onClose, showToast, selectedItem, update, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        return errorMessages.length == 0 ;
    }
    const emptyItem = new ModelPermissionDto();


    const {
        item,
        setItem,
        submitted,
        setSubmitted,
        activeIndex,
        setActiveIndex,
        activeTab,
        setActiveTab,
        onInputTextChange,
        onInputDateChange,
        onInputNumerChange,
        onMultiSelectChange,
        onBooleanInputChange,
        onDropdownChange,
        onTabChange,
        hideDialog,
        editItem,
        formateDate,
        parseToIsoFormat,
        adaptDate
        } = useEditHook<ModelPermissionDto, ModelPermissionCriteria>({list, selectedItem, onClose, update, showToast,service, t, isFormValid})



    useEffect(() => {


        }, []);







    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" onClick={editItem} /> </>
    );



    return(
    <Dialog visible={visible} style={{width: '70vw'}} header={t("modelPermission.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog}>
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("modelPermission.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="reference">{t("modelPermission.reference")}</label>
                        <InputText id="reference" value={item ? item.reference : ''} onChange={(e) => onInputTextChange(e, 'reference')} required className={classNames({'p-invalid': submitted && !item.reference})} />
                        {submitted && !item.reference && <small className="p-invalid">Reference is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="libelle">{t("modelPermission.libelle")}</label>
                        <InputText id="libelle" value={item ? item.libelle : ''} onChange={(e) => onInputTextChange(e, 'libelle')} required className={classNames({'p-invalid': submitted && !item.libelle})} />
                        {submitted && !item.libelle && <small className="p-invalid">Libelle is required.</small>}
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Edit;

// laravel/v3/frontend/src/app/module/admin/view/security/model-permission/edit/model-permission-edit-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';


import {AbstractEditController} from 'src/app/zynerator/controller/AbstractEditController';

import {ModelPermissionAdminService} from 'src/app/controller/service/admin/security/ModelPermissionAdmin.service';
import {ModelPermissionDto} from 'src/app/controller/model/security/ModelPermission.model';
import {ModelPermissionCriteria} from 'src/app/controller/criteria/security/ModelPermissionCriteria.model';



@Component({
  selector: 'app-model-permission-edit-admin',
  templateUrl: './model-permission-edit-admin.component.html'
})
export class ModelPermissionEditAdminComponent extends AbstractEditController<ModelPermissionDto, ModelPermissionCriteria, ModelPermissionAdminService>   implements OnInit {






    constructor( private modelPermissionService: ModelPermissionAdminService ) {
        super(modelPermissionService);
    }

    ngOnInit(): void {
    }


    public setValidation(value: boolean){
        }
    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }







}

        <p-dialog [(visible)]="editDialog" [style]="{width: '70vw'}" header="{{'modelPermission.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                <p-tabView>
                    <p-tabPanel header="{{'modelPermission.tabPan' | translate}}">
                        <div class="grid">

                                        <div class="field col-12 md:col-6">
                                            <label for="1">{{'modelPermission.reference' | translate}}</label>
                                            <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'modelPermission.reference' | translate}}" id="1" [(ngModel)]="item.reference"
                                                     />
                                            
                                        </div>



                                        <div class="field col-12 md:col-6">
                                            <label for="2">{{'modelPermission.libelle' | translate}}</label>
                                            <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'modelPermission.libelle' | translate}}" id="2" [(ngModel)]="item.libelle"
                                                     />
                                            
                                        </div>



                        </div>
                    </p-tabPanel>

                </p-tabView>
            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-footer">
                        <div>
                            <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideEditDialog()"></button>
                        </div>
                    <div>
                        <button pButton pRipple label="Valider" icon="pi pi-check" style="margin:10px" (click)="edit()"></button>
                    </div>
                </div>
            </ng-template>



    </p-dialog>
