// laravel/v3/frontend/src/app/module/admin/view/security/role/edit/role-edit-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';


import {AbstractEditController} from 'src/app/zynerator/controller/AbstractEditController';

import {RoleAdminService} from 'src/app/controller/service/admin/security/RoleAdmin.service';
import {RoleDto} from 'src/app/controller/model/security/Role.model';
import {RoleCriteria} from 'src/app/controller/criteria/security/RoleCriteria.model';



@Component({
  selector: 'app-role-edit-admin',
  templateUrl: './role-edit-admin.component.html'
})
export class RoleEditAdminComponent extends AbstractEditController<RoleDto, RoleCriteria, RoleAdminService>   implements OnInit {






    constructor( private roleService: RoleAdminService ) {
        super(roleService);
    }

    ngOnInit(): void {
    }


    public setValidation(value: boolean){
        }
    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }







}

        <p-dialog [(visible)]="editDialog" [style]="{width: '70vw'}" header="{{'role.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                <p-tabView>
                    <p-tabPanel header="{{'role.tabPan' | translate}}">
                        <div class="grid">

                                        <div class="field col-12 md:col-6">
                                            <label for="1">{{'role.authority' | translate}}</label>
                                            <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'role.authority' | translate}}" id="1" [(ngModel)]="item.authority"
                                                     />
                                            
                                        </div>



                        </div>
                    </p-tabPanel>

                </p-tabView>
            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-footer">
                        <div>
                            <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideEditDialog()"></button>
                        </div>
                    <div>
                        <button pButton pRipple label="Valider" icon="pi pi-check" style="margin:10px" (click)="edit()"></button>
                    </div>
                </div>
            </ng-template>



    </p-dialog>

// next/security/frontend/components/admin/view/security/role/edit/role-edit-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar} from 'primereact/calendar';
import { format } from 'date-fns';
import { parse } from 'date-fns';
import { InputSwitch } from 'primereact/inputswitch';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';


import {MessageService} from '@/utils/zynerator/service/MessageService';


import {TFunction} from "i18next";
import {Toast} from "primereact/toast";

import useEditHook from "@/utils/zyhook/useEdit.hook";


import {RoleAdminService} from '@/controller/service/admin/security/RoleAdminService.service';
import  {RoleDto}  from '@/controller/model/security/Role.model';
import {RoleCriteria} from "@/controller/criteria/security/RoleCriteria.model";




type RoleEditAdminType = {
    visible: boolean,
    onClose: () => void,
    showToast: React.Ref<Toast>,
    selectedItem: RoleDto
    update: (item: RoleDto) => void,
    list: RoleDto[],
    service: RoleAdminService,
    t: TFunction
}
const Edit: React.FC<RoleEditAdminType> = ({visible, onClose, showToast, selectedItem, update, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        return errorMessages.length == 0 ;
    }
    const emptyItem = new RoleDto();


    const {
        item,
        setItem,
        submitted,
        setSubmitted,
        activeIndex,
        setActiveIndex,
        activeTab,
        setActiveTab,
        onInputTextChange,
        onInputDateChange,
        onInputNumerChange,
        onMultiSelectChange,
        onBooleanInputChange,
        onDropdownChange,
        onTabChange,
        hideDialog,
        editItem,
        formateDate,
        parseToIsoFormat,
        adaptDate
        } = useEditHook<RoleDto, RoleCriteria>({list, selectedItem, onClose, update, showToast,service, t, isFormValid})



    useEffect(() => {


        }, []);







    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" onClick={editItem} /> </>
    );



    return(
    <Dialog visible={visible} style={{width: '70vw'}} header={t("role.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog}>
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("role.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="authority">{t("role.authority")}</label>
                        <InputText id="authority" value={item ? item.authority : ''} onChange={(e) => onInputTextChange(e, 'authority')} required className={classNames({'p-invalid': submitted && !item.authority})} />
                        {submitted && !item.authority && <small className="p-invalid">Authority is required.</small>}
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Edit;
