// laravel/v3/frontend/src/app/module/admin/view/security/action-permission/create/action-permission-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {ActionPermissionAdminService} from 'src/app/controller/service/admin/security/ActionPermissionAdmin.service';
import {ActionPermissionDto} from 'src/app/controller/model/security/ActionPermission.model';
import {ActionPermissionCriteria} from 'src/app/controller/criteria/security/ActionPermissionCriteria.model';
@Component({
  selector: 'app-action-permission-create-admin',
  templateUrl: './action-permission-create-admin.component.html'
})
export class ActionPermissionCreateAdminComponent extends AbstractCreateController<ActionPermissionDto, ActionPermissionCriteria, ActionPermissionAdminService>  implements OnInit {




    constructor( private actionPermissionService: ActionPermissionAdminService ) {
        super(actionPermissionService);
    }

    ngOnInit(): void {
    }





    public setValidation(value: boolean){
    }



    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }










}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'actionPermission.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'actionPermission.tabPan' | translate}}">
                                <div class="grid">

                                                <div class="field col-12 md:col-6">
                                                    <label for="1">{{'actionPermission.reference' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'actionPermission.reference' | translate}}" id="1" [(ngModel)]="item.reference"
                                                             />
                                                    
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="2">{{'actionPermission.libelle' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'actionPermission.libelle' | translate}}" id="2" [(ngModel)]="item.libelle"
                                                             />
                                                    
                                                </div>



                                </div>
                            </p-tabPanel>

                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>



    </p-dialog>

// next/security/frontend/components/admin/view/security/action-permission/create/action-permission-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import { Calendar } from 'primereact/calendar';
import { format } from 'date-fns';
import {InputSwitch, InputSwitchChangeEvent} from 'primereact/inputswitch';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';
import {MessageService} from '@/utils/zynerator/service/MessageService';

import {ActionPermissionAdminService} from '@/controller/service/admin/security/ActionPermissionAdminService.service';
import  {ActionPermissionDto}  from '@/controller/model/security/ActionPermission.model';
import {ActionPermissionCriteria} from "@/controller/criteria/security/ActionPermissionCriteria.model";

import {TFunction} from "i18next";
import {Toast} from "primereact/toast";
import useCreateHook from "@/utils/zyhook/useCreate.hook";



type ActionPermissionCreateAdminType = {
    visible: boolean,
    onClose: () => void,
    add: (item: ActionPermissionDto) => void,
    showToast: React.Ref<Toast>,
    list: ActionPermissionDto[],
    service: ActionPermissionAdminService,
    t: TFunction
}
const Create: React.FC<ActionPermissionCreateAdminType> = ({visible, onClose, add, showToast, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        return errorMessages.length == 0 ;
    }
    const emptyItem = new ActionPermissionDto();
        const {
            item,
            setItem,
            submitted,
            setSubmitted,
            activeIndex,
            setActiveIndex,
            activeTab,
            setActiveTab,
            onInputTextChange,
            onInputDateChange,
            onInputNumerChange,
            onMultiSelectChange,
            onBooleanInputChange,
            onTabChange,
            onDropdownChange,
            hideDialog,
            saveItem,
            formateDate
        } = useCreateHook<ActionPermissionDto, ActionPermissionCriteria>({list, emptyItem, onClose, add, showToast,service, isFormValid})


    useEffect(() => {
    }, []);








    const itemDialogFooter = ( <>
        <Button label={t("cancel")} icon="pi pi-times" text onClick={hideDialog} />
        <Button label={t("save")} icon="pi pi-check" onClick={saveItem} /> </>
    );

return(
        <Dialog visible={visible} style={{width: '70vw'}} header={t("actionPermission.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("actionPermission.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <label htmlFor="reference">{t("actionPermission.reference")}</label>
                        <InputText id="reference" value={item.reference} onChange={(e) => onInputTextChange(e, 'reference')} required className={classNames({'p-invalid': submitted && !item.reference})} />
                        {submitted && !item.reference && <small className="p-invalid">Reference is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="libelle">{t("actionPermission.libelle")}</label>
                        <InputText id="libelle" value={item.libelle} onChange={(e) => onInputTextChange(e, 'libelle')} required className={classNames({'p-invalid': submitted && !item.libelle})} />
                        {submitted && !item.libelle && <small className="p-invalid">Libelle is required.</small>}
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;
