// spring-angular/sakai/v1/frontend/src/app/layout/app.menu.component.ts
import { OnInit } from '@angular/core';
import { Component } from '@angular/core';
import {Router} from '@angular/router';

import { LayoutService } from './service/app.layout.service';
import {AppComponent} from 'src/app/app.component';

import {RoleService} from 'src/app/zynerator/security/controller/service/Role.service';
import {AuthService} from 'src/app/zynerator/security/controller/service/Auth.service';

import {AppLayoutComponent} from 'src/app/layout/app.layout.component';


@Component({
  selector: 'app-menu',
  templateUrl: './app.menu.component.html'
})
export class AppMenuComponent implements OnInit {
  model: any[];
  modelanonymous: any[];
    modelAdmin: any[];
constructor(public layoutService: LayoutService, public app: AppComponent, public appMain: AppLayoutComponent, private roleService: RoleService, private authService: AuthService, private router: Router) { }

  ngOnInit() {
    this.modelAdmin =
      [


              {
                label: 'Client',
                icon: 'pi pi-wallet',
                items: [
                          {
                            label: 'Liste client',
                            icon: 'pi pi-fw pi-plus-circle',
                            routerLink: ['/app/admin/commun/client/list']
                          },
                ]
              },

           {
              label: 'Security Management',
              icon: 'pi pi-wallet',
              items: [
                  {
                      label: 'List User',
                      icon: 'pi pi-fw pi-plus-circle',
                      routerLink: ['/app/admin/security/user/list']
                  },
                  {
                      label: 'List Model',
                      icon: 'pi pi-fw pi-plus-circle',
                      routerLink: ['/app/admin/security/model-permission/list']
                  },
                  {
                      label: 'List Action Permission',
                      icon: 'pi pi-fw pi-plus-circle',
                      routerLink: ['/app/admin/security/action-permission/list']
                  },
              ]
          }
    ];
        if (this.authService.authenticated) {
            if (this.authService.authenticatedUser.roleUsers) {
              this.authService.authenticatedUser.roleUsers.forEach(role => {
                  const roleName: string = this.getRole(role.role.authority);
                  this.roleService._role.next(roleName.toUpperCase());
                  eval('this.model = this.model' + this.getRole(role.role.authority));
              })
            }
        }
  }

    getRole(text){
        const [role, ...rest] = text.split('_');
        return this.upperCaseFirstLetter(rest.join(''));
    }

    upperCaseFirstLetter(word: string) {
      if (!word) { return word; }
      return word[0].toUpperCase() + word.substr(1).toLowerCase();
    }

    onMenuClick(event) {
        this.appMain.onMenuClick(event);
    }
}

<div class="layout-menu-container" (click)="onMenuClick($event)">
    <div class="menu-scroll-content">

               <p-panelMenu [model]="model" [style]="{'width':'275px'}"></p-panelMenu>
    </div>
</div>
<!--<ul class="layout-menu">-->
<!--    <ng-container *ngFor="let item of model; let i = index;">-->
<!--        <li app-menuitem  [item]="item" [index]="i" [root]="true"></li>-->
<!--        <li  class="menu-separator"></li>-->
<!--    </ng-container>-->

<!--</ul>-->

// next/security/user and permission/frontend/layout/AppMenu.tsx
/* eslint-disable @next/next/no-img-element */
"use client"
import { AppMenuItem } from '@/types';
import { MenuProvider } from './context/menucontext';
import AppMenuitem from './AppMenuitem';
import {AuthService} from '@/utils/zynerator/security/Auth.service';
import React, {useEffect, useState} from 'react';


const AppMenu = () => {

    const [model,setModel] = useState<AppMenuItem[]>([] as AppMenuItem[]);
    const authService = new AuthService();
        const modelAdmin: AppMenuItem[] = [
        {
            label: 'Home',
            items: [{label: 'Dashboard', icon: 'pi pi-fw pi-home', to: '/'}]
        },


        {
            label: 'Pages',
            icon: 'pi pi-fw pi-briefcase',
            to: '',
            items: [

                {
                    label: 'Auth',
                    icon: 'pi pi-fw pi-user',
                    items: [
                        {
                            label: 'Error',
                            icon: 'pi pi-fw pi-times-circle',
                            to: '/auth/error'
                        },
                        {
                            label: 'Access Denied',
                            icon: 'pi pi-fw pi-lock',
                            to: '/auth/access'
                        }
                    ]
                },
                {
                    label: 'Security Management',
                    icon: 'pi pi-fw pi-plus-circle',
                    items: [
                      {
                      label: 'Liste role',
                     to: '/admin/view/security/role'
                      },
                      {
                      label: 'Liste model permission user',
                     to: '/admin/view/security/model-permission-user'
                      },
                      {
                      label: 'Liste action permission',
                     to: '/admin/view/security/action-permission'
                      },
                      {
                      label: 'Liste model permission',
                     to: '/admin/view/security/model-permission'
                      },
                      {
                      label: 'Liste user',
                     to: '/admin/view/security/user'
                      },
                    ]
                    },
            ]
        },

    ];

    useEffect(()=>{
        const roleConnectedUser = authService.getRoleConnectedUser();
        if(roleConnectedUser === 'ROLE_ADMIN'){
            setModel(modelAdmin)
        }
    },[])

    return (
        <MenuProvider>
            <ul className="layout-menu">
                {model.map((item, i) => {
                    return !item?.seperator ? <AppMenuitem item={item} root={true} index={i} key={item.label}/> :
                        <li className="menu-separator"></li>;
                })}


            </ul>
        </MenuProvider>
    );
};


export default AppMenu;
