// laravel/v3/frontend/src/app/module/admin/view/security/user/create/user-create-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';

import { AbstractCreateController } from 'src/app/zynerator/controller/AbstractCreateController';

import {UserAdminService} from 'src/app/controller/service/admin/security/UserAdmin.service';
import {UserDto} from 'src/app/controller/model/security/User.model';
import {UserCriteria} from 'src/app/controller/criteria/security/UserCriteria.model';
import {RoleDto} from 'src/app/controller/model/security/Role.model';
import {RoleAdminService} from 'src/app/controller/service/admin/security/RoleAdmin.service';
import {ModelPermissionUserDto} from 'src/app/controller/model/security/ModelPermissionUser.model';
import {ModelPermissionUserAdminService} from 'src/app/controller/service/admin/security/ModelPermissionUserAdmin.service';
import {ModelPermissionDto} from 'src/app/controller/model/security/ModelPermission.model';
import {ModelPermissionAdminService} from 'src/app/controller/service/admin/security/ModelPermissionAdmin.service';
import {RoleUserDto} from 'src/app/controller/model/security/RoleUser.model';
import {RoleUserAdminService} from 'src/app/controller/service/admin/security/RoleUserAdmin.service';
import {ActionPermissionDto} from 'src/app/controller/model/security/ActionPermission.model';
import {ActionPermissionAdminService} from 'src/app/controller/service/admin/security/ActionPermissionAdmin.service';
@Component({
  selector: 'app-user-create-admin',
  templateUrl: './user-create-admin.component.html'
})
export class UserCreateAdminComponent extends AbstractCreateController<UserDto, UserCriteria, UserAdminService>  implements OnInit {

    private _roleUsersElement = new RoleUserDto();
    private _modelPermissionUsersElement = new ModelPermissionUserDto();


    private _roleUsers: Array<RoleUserDto> = [];

    constructor( private userService: UserAdminService , private roleService: RoleAdminService, private modelPermissionUserService: ModelPermissionUserAdminService, private modelPermissionService: ModelPermissionAdminService, private roleUserService: RoleUserAdminService, private actionPermissionService: ActionPermissionAdminService) {
        super(userService);
    }

    ngOnInit(): void {
        this.roleService.findAll().subscribe(data => this.prepareRoleUsers(data));
        this.roleUsersElement.role = new RoleDto();
        this.roleService.findAll().subscribe((data) => this.roles = data);
        this.modelPermissionUsersElement.actionPermission = new ActionPermissionDto();
        this.actionPermissionService.findAll().subscribe((data) => this.actionPermissions = data);
        this.modelPermissionUsersElement.modelPermission = new ModelPermissionDto();
        this.modelPermissionService.findAll().subscribe((data) => this.modelPermissions = data);
    }


     prepareRoleUsers(roles: Array<RoleDto>): void{
        if( roles != null){
                roles.forEach(e => {
                const roleUser = new RoleUserDto();
                roleUser.role = e;
                this.roleUsers.push(roleUser);
            });
        }
    }

    validateModelPermissionUsers(){
        this.errorMessages = new Array();
    }


    public setValidation(value: boolean){
    }

    public addModelPermissionUsers() {
        if( this.item.modelPermissionUsers == null )
            this.item.modelPermissionUsers = new Array<ModelPermissionUserDto>();
       this.validateModelPermissionUsers();
       if (this.errorMessages.length === 0) {
              this.item.modelPermissionUsers.push({... this.modelPermissionUsersElement});
              this.modelPermissionUsersElement = new ModelPermissionUserDto();
       }else{
            this.messageService.add({severity: 'error',summary: 'Erreurs',detail: 'Merci de corrigé les erreurs suivant : ' + this.errorMessages});
       }
    }


    public deletemodelPermissionUsers(p: ModelPermissionUserDto) {
        this.item.modelPermissionUsers.forEach((element, index) => {
            if (element === p) { this.item.modelPermissionUsers.splice(index, 1); }
        });
    }

    public editmodelPermissionUsers(p: ModelPermissionUserDto) {
        this.modelPermissionUsersElement = {... p};
        this.activeTab = 0;
    }


    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }



    public async openCreateRole(role: string) {
    const isPermistted = await this.roleService.isPermitted('Role', 'add');
    if(isPermistted) {
         this.role = new RoleDto();
         this.createRoleDialog = true;
    }else{
        this.messageService.add({
        severity: 'error', summary: 'erreur', detail: 'problème de permission'
        });
     }
    }
    public async openCreateModelPermission(modelPermission: string) {
    const isPermistted = await this.roleService.isPermitted('ModelPermission', 'add');
    if(isPermistted) {
         this.modelPermission = new ModelPermissionDto();
         this.createModelPermissionDialog = true;
    }else{
        this.messageService.add({
        severity: 'error', summary: 'erreur', detail: 'problème de permission'
        });
     }
    }
    public async openCreateActionPermission(actionPermission: string) {
    const isPermistted = await this.roleService.isPermitted('ActionPermission', 'add');
    if(isPermistted) {
         this.actionPermission = new ActionPermissionDto();
         this.createActionPermissionDialog = true;
    }else{
        this.messageService.add({
        severity: 'error', summary: 'erreur', detail: 'problème de permission'
        });
     }
    }

    get role(): RoleDto {
        return this.roleService.item;
    }
    set role(value: RoleDto) {
        this.roleService.item = value;
    }
    get roles(): Array<RoleDto> {
        return this.roleService.items;
    }
    set roles(value: Array<RoleDto>) {
        this.roleService.items = value;
    }
    get createRoleDialog(): boolean {
       return this.roleService.createDialog;
    }
    set createRoleDialog(value: boolean) {
        this.roleService.createDialog= value;
    }
    get modelPermission(): ModelPermissionDto {
        return this.modelPermissionService.item;
    }
    set modelPermission(value: ModelPermissionDto) {
        this.modelPermissionService.item = value;
    }
    get modelPermissions(): Array<ModelPermissionDto> {
        return this.modelPermissionService.items;
    }
    set modelPermissions(value: Array<ModelPermissionDto>) {
        this.modelPermissionService.items = value;
    }
    get createModelPermissionDialog(): boolean {
       return this.modelPermissionService.createDialog;
    }
    set createModelPermissionDialog(value: boolean) {
        this.modelPermissionService.createDialog= value;
    }
    get actionPermission(): ActionPermissionDto {
        return this.actionPermissionService.item;
    }
    set actionPermission(value: ActionPermissionDto) {
        this.actionPermissionService.item = value;
    }
    get actionPermissions(): Array<ActionPermissionDto> {
        return this.actionPermissionService.items;
    }
    set actionPermissions(value: Array<ActionPermissionDto>) {
        this.actionPermissionService.items = value;
    }
    get createActionPermissionDialog(): boolean {
       return this.actionPermissionService.createDialog;
    }
    set createActionPermissionDialog(value: boolean) {
        this.actionPermissionService.createDialog= value;
    }

    get roleUsers(): Array<RoleUserDto> {
        if( this._roleUsers == null )
            this._roleUsers = new Array();
        return this._roleUsers;
    }

    set roleUsers(value: Array<RoleUserDto>) {
        this._roleUsers = value;
    }




    get roleUsersElement(): RoleUserDto {
        if( this._roleUsersElement == null )
            this._roleUsersElement = new RoleUserDto();
        return this._roleUsersElement;
    }

    set roleUsersElement(value: RoleUserDto) {
        this._roleUsersElement = value;
    }
    get modelPermissionUsersElement(): ModelPermissionUserDto {
        if( this._modelPermissionUsersElement == null )
            this._modelPermissionUsersElement = new ModelPermissionUserDto();
        return this._modelPermissionUsersElement;
    }

    set modelPermissionUsersElement(value: ModelPermissionUserDto) {
        this._modelPermissionUsersElement = value;
    }

}

        <p-dialog [(visible)]="createDialog" [style]="{width: '70vw'}" header="{{'user.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                        <p-tabView>
                            <p-tabPanel header="{{'user.tabPan' | translate}}">
                                <div class="grid">

                                                <div class="field align-inputswitch col-12  md:col-6">
                                                    <div  class="label-inputswitch">
                                                        <label for="1">{{'user.credentialsNonExpired' | translate}}</label>
                                                    </div>
                                                    <div class="input-switch">
                                                        <p-inputSwitch id="1"  [(ngModel)]="item.credentialsNonExpired"
                                                                 >
                                                        </p-inputSwitch>
                                                        
                                                    </div>
                                                </div>


                                                <div class="field align-inputswitch col-12  md:col-6">
                                                    <div  class="label-inputswitch">
                                                        <label for="2">{{'user.enabled' | translate}}</label>
                                                    </div>
                                                    <div class="input-switch">
                                                        <p-inputSwitch id="2"  [(ngModel)]="item.enabled"
                                                                 >
                                                        </p-inputSwitch>
                                                        
                                                    </div>
                                                </div>


                                                <div class="field col-12 md:col-6">
                                                    <label for="3">{{'user.email' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.email' | translate}}" id="3" [(ngModel)]="item.email"
                                                             />
                                                    
                                                </div>



                                                <div class="field align-inputswitch col-12  md:col-6">
                                                    <div  class="label-inputswitch">
                                                        <label for="4">{{'user.accountNonExpired' | translate}}</label>
                                                    </div>
                                                    <div class="input-switch">
                                                        <p-inputSwitch id="4"  [(ngModel)]="item.accountNonExpired"
                                                                 >
                                                        </p-inputSwitch>
                                                        
                                                    </div>
                                                </div>


                                                <div class="field align-inputswitch col-12  md:col-6">
                                                    <div  class="label-inputswitch">
                                                        <label for="5">{{'user.accountNonLocked' | translate}}</label>
                                                    </div>
                                                    <div class="input-switch">
                                                        <p-inputSwitch id="5"  [(ngModel)]="item.accountNonLocked"
                                                                 >
                                                        </p-inputSwitch>
                                                        
                                                    </div>
                                                </div>


                                                <div class="field col-12 md:col-6">
                                                    <label for="6">{{'user.username' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.username' | translate}}" id="6" [(ngModel)]="item.username"
                                                             />
                                                    
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="7">{{'user.password' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.password' | translate}}" id="7" [(ngModel)]="item.password"
                                                             />
                                                    
                                                </div>



                                                <div class="field align-inputswitch col-12  md:col-6">
                                                    <div  class="label-inputswitch">
                                                        <label for="8">{{'user.passwordChanged' | translate}}</label>
                                                    </div>
                                                    <div class="input-switch">
                                                        <p-inputSwitch id="8"  [(ngModel)]="item.passwordChanged"
                                                                 >
                                                        </p-inputSwitch>
                                                        
                                                    </div>
                                                </div>


                                                <div class="field col-12 md:col-6">
                                                    <label for="9">{{'user.lastName' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.lastName' | translate}}" id="9" [(ngModel)]="item.lastName"
                                                             />
                                                    
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="10">{{'user.firstName' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.firstName' | translate}}" id="10" [(ngModel)]="item.firstName"
                                                             />
                                                    
                                                </div>



                                                <div class="field col-12 md:col-6">
                                                    <label for="11">{{'user.phone' | translate}}</label>
                                                    <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'user.phone' | translate}}" id="11" [(ngModel)]="item.phone"
                                                             />
                                                    
                                                </div>



                                            <div class="field col-12  md:col-6">
                                                <label>Role</label>
                                                <p-multiSelect [options]="roleUsers" [(ngModel)]="item.roleUsers" itemSize="30" [virtualScroll]="true"
                                                                                                                          defaultLabel="Select un role" optionLabel="role.authority"  display="chip"></p-multiSelect>
                                            </div>
                                </div>
                            </p-tabPanel>
                                    <p-tabPanel header="{{'user.modelPermissionUsers' | translate}}">
                                                <div class="p-col">
                                                    <div class="grid">
                                                                    <div class="field  align-inputswitch col-12 md:col-6">
                                                                        <div  class="label-inputswitch">
                                                                            <label for="1">Value</label>
                                                                        </div>
                                                                        <div class="input-switch">
                                                                            <p-inputSwitch id="1"  [(ngModel)]="modelPermissionUsersElement.value"></p-inputSwitch>
                                                                        </div>
                                                                    </div>
                                                                    <div class="field col-12 md:col-6">
                                                                        <label for="2">Sub attribute</label>
                                                                        <input class="mb-2 mr-2" type="text" pInputText placeholder="Sub attribute"
                                                                               id="2" [(ngModel)]="modelPermissionUsersElement.subAttribute" autofocus   >
                                                                        
                                                                    </div>
                                                                    <div class="field col-11 md:col-5">
                                                                        <label>Action permission</label>
                                                                        <p-dropdown  appendTo="body"  [options]="actionPermissions" [(ngModel)]="modelPermissionUsersElement.actionPermission"
                                                                                     id="3"  [filter]="true" filterMatchMode="contains" [showClear]="true" optionLabel="id"
                                                                                     placeholder="Action permission"  >
                                                                        </p-dropdown>
                                                                        
                                                                    </div>
                                                                    <div class="col-1">
                                                                        <label></label>
                                                                        <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateActionPermission('actionPermission')" class="p-button-success one-colonne-btn-success-align"></button>
                                                                    </div>
                                                                    <div class="field col-11 md:col-5">
                                                                        <label>Model permission</label>
                                                                        <p-dropdown  appendTo="body"  [options]="modelPermissions" [(ngModel)]="modelPermissionUsersElement.modelPermission"
                                                                                     id="4"  [filter]="true" filterMatchMode="contains" [showClear]="true" optionLabel="id"
                                                                                     placeholder="Model permission"  >
                                                                        </p-dropdown>
                                                                        
                                                                    </div>
                                                                    <div class="col-1">
                                                                        <label></label>
                                                                        <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateModelPermission('modelPermission')" class="p-button-success one-colonne-btn-success-align"></button>
                                                                    </div>
                                                        <div class="field col-12 md:col-1">
                                                            <button pButton pRipple type="button" icon="pi pi-plus" class="mt-4" label="OK" (click)="addModelPermissionUsers()"></button>
                                                        </div>

                                                    </div>
                                                </div>
                                                <div class="p-col">
                                                    <div class="card">
                                                        <p-table [value]="item.modelPermissionUsers" [scrollable]="true" scrollHeight="200px">
                                                            <ng-template pTemplate="header">
                                                                <tr>
                                                                                <th>Value</th>
                                                                                <th>Sub attribute</th>
                                                                                <th>Action permission</th>
                                                                                <th>Model permission</th>
                                                                    <th>Actions</th>
                                                                </tr>
                                                            </ng-template>
                                                            <ng-template pTemplate="body" let-p>
                                                                <tr>
                                                                                <td><i *ngIf="p.value" class="pi pi-check checked-toogle"></i>
                                                                                    <i *ngIf="!p.value" class="pi pi-times unchecked-toogle"></i>
                                                                                </td>
                                                                                <td>{{p.subAttribute}}</td>
                                                                            <td>{{p.actionPermission?.id}}</td>
                                                                            <td>{{p.modelPermission?.id}}</td>
                                                                    <td>
                                                                        <button (click)="deleteModelPermissionUsers(p)" pButton type="button" icon="pi pi-times"  class="p-button-rounded p-button-danger"></button>
                                                                        <button (click)="editModelPermissionUsers(p)" pButton type="button" icon="pi pi-pencil" class="p-button-rounded p-button-success mr-2"></button>
                                                                    </td>
                                                                </tr>
                                                            </ng-template>
                                                        </p-table>
                                                    </div>

                                                </div>
                                    </p-tabPanel>


                        </p-tabView>

            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-step">
                        <div style="margin-left: auto;">
                            <button pButton pRipple  label="{{'validate' | translate}}"  icon="pi pi-check" style="margin:10px" (click)="save()"></button>
                        </div>
                        <div>
                            <button pButton pRipple  label="{{'cancel' | translate}}" icon="pi pi-times" class="p-button-outlined" (click)="hideCreateDialog()"></button>
                        </div>

                </div>
            </ng-template>


            <app-role-create-admin></app-role-create-admin>
            <app-action-permission-create-admin></app-action-permission-create-admin>
            <app-model-permission-create-admin></app-model-permission-create-admin>

    </p-dialog>

// next/security/frontend/components/admin/view/security/user/create/user-create-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {TabView, TabPanel} from 'primereact/tabview';
import {DataTable} from 'primereact/datatable';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import { Calendar } from 'primereact/calendar';
import { format } from 'date-fns';
import {InputSwitch, InputSwitchChangeEvent} from 'primereact/inputswitch';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';
import {MessageService} from '@/utils/zynerator/service/MessageService';

import {UserAdminService} from '@/controller/service/admin/security/UserAdminService.service';
import  {UserDto}  from '@/controller/model/security/User.model';
import {UserCriteria} from "@/controller/criteria/security/UserCriteria.model";

import {RoleDto} from '@/controller/model/security/Role.model';
import {RoleAdminService} from '@/controller/service/admin/security/RoleAdminService.service';
import {RoleUserDto} from '@/controller/model/security/RoleUser.model';
import {RoleUserAdminService} from '@/controller/service/admin/security/RoleUserAdminService.service';
import {TFunction} from "i18next";
import {Toast} from "primereact/toast";
import useCreateHook from "@/utils/zyhook/useCreate.hook";



type UserCreateAdminType = {
    visible: boolean,
    onClose: () => void,
    add: (item: UserDto) => void,
    showToast: React.Ref<Toast>,
    list: UserDto[],
    service: UserAdminService,
    t: TFunction
}
const Create: React.FC<UserCreateAdminType> = ({visible, onClose, add, showToast, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        return errorMessages.length == 0 ;
    }
    const emptyItem = new UserDto();
        const {
            item,
            setItem,
            submitted,
            setSubmitted,
            activeIndex,
            setActiveIndex,
            activeTab,
            setActiveTab,
            onInputTextChange,
            onInputDateChange,
            onInputNumerChange,
            onMultiSelectChange,
            onBooleanInputChange,
            onTabChange,
            onDropdownChange,
            hideDialog,
            saveItem,
            formateDate
        } = useCreateHook<UserDto, UserCriteria>({list, emptyItem, onClose, add, showToast,service, isFormValid})
    const [roles, setRoles] = useState<RoleDto[]>([]);

    const [roleUsers, setRoleUsers] = useState<RoleUserDto>(new RoleUserDto());

    const roleAdminService = new RoleAdminService();
    const roleUserAdminService = new RoleUserAdminService();
    useEffect(() => {
        roleAdminService.getList().then(({data}) => {
            const RoleUsers = data?.map(prepareRoleUser)
            setRoleUsers(roleUsers)
        })



    }, []);


    const prepareRoleUser = (role: RoleDto) => {
        const roleUser = new RoleUserDto();
        roleUser.role = role;
        return roleUser;
    }






    const itemDialogFooter = ( <>
        <Button label={t("cancel")} icon="pi pi-times" text onClick={hideDialog} />
        <Button label={t("save")} icon="pi pi-check" onClick={saveItem} /> </>
    );

return(
        <Dialog visible={visible} style={{width: '70vw'}} header={t("user.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog} >
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("user.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                    <div  className="label-inputswitch">
                        <label htmlFor="credentialsNonExpired">{t("user.credentialsNonExpired")}</label>
                        <span className="p-float-label">
                        <InputSwitch  id="credentialsNonExpired" checked={item.credentialsNonExpired} onChange={(e) => onBooleanInputChange(e, 'credentialsNonExpired')} />
                        </span>
                    </div>
                    </div>
                    <div className="field col-6">
                    <div  className="label-inputswitch">
                        <label htmlFor="enabled">{t("user.enabled")}</label>
                        <span className="p-float-label">
                        <InputSwitch  id="enabled" checked={item.enabled} onChange={(e) => onBooleanInputChange(e, 'enabled')} />
                        </span>
                    </div>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="email">{t("user.email")}</label>
                        <InputText id="email" value={item.email} onChange={(e) => onInputTextChange(e, 'email')} required className={classNames({'p-invalid': submitted && !item.email})} />
                        {submitted && !item.email && <small className="p-invalid">Email is required.</small>}
                    </div>
                    <div className="field col-6">
                    <div  className="label-inputswitch">
                        <label htmlFor="accountNonExpired">{t("user.accountNonExpired")}</label>
                        <span className="p-float-label">
                        <InputSwitch  id="accountNonExpired" checked={item.accountNonExpired} onChange={(e) => onBooleanInputChange(e, 'accountNonExpired')} />
                        </span>
                    </div>
                    </div>
                    <div className="field col-6">
                    <div  className="label-inputswitch">
                        <label htmlFor="accountNonLocked">{t("user.accountNonLocked")}</label>
                        <span className="p-float-label">
                        <InputSwitch  id="accountNonLocked" checked={item.accountNonLocked} onChange={(e) => onBooleanInputChange(e, 'accountNonLocked')} />
                        </span>
                    </div>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="username">{t("user.username")}</label>
                        <InputText id="username" value={item.username} onChange={(e) => onInputTextChange(e, 'username')} required className={classNames({'p-invalid': submitted && !item.username})} />
                        {submitted && !item.username && <small className="p-invalid">Username is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="password">{t("user.password")}</label>
                        <InputText id="password" value={item.password} onChange={(e) => onInputTextChange(e, 'password')} required className={classNames({'p-invalid': submitted && !item.password})} />
                        {submitted && !item.password && <small className="p-invalid">Password is required.</small>}
                    </div>
                    <div className="field col-6">
                    <div  className="label-inputswitch">
                        <label htmlFor="passwordChanged">{t("user.passwordChanged")}</label>
                        <span className="p-float-label">
                        <InputSwitch  id="passwordChanged" checked={item.passwordChanged} onChange={(e) => onBooleanInputChange(e, 'passwordChanged')} />
                        </span>
                    </div>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="lastName">{t("user.lastName")}</label>
                        <InputText id="lastName" value={item.lastName} onChange={(e) => onInputTextChange(e, 'lastName')} required className={classNames({'p-invalid': submitted && !item.lastName})} />
                        {submitted && !item.lastName && <small className="p-invalid">LastName is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="firstName">{t("user.firstName")}</label>
                        <InputText id="firstName" value={item.firstName} onChange={(e) => onInputTextChange(e, 'firstName')} required className={classNames({'p-invalid': submitted && !item.firstName})} />
                        {submitted && !item.firstName && <small className="p-invalid">FirstName is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="phone">{t("user.phone")}</label>
                        <InputText id="phone" value={item.phone} onChange={(e) => onInputTextChange(e, 'phone')} required className={classNames({'p-invalid': submitted && !item.phone})} />
                        {submitted && !item.phone && <small className="p-invalid">Phone is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="roleUsers">{t("roleUser.role")}</label>
                        {/*
                        <MultiSelect value={item.roleUsers} options={roleUsers}  optionLabel="role.authority" display="chip" placeholder={t("user.roleUsersPlaceHolder")}  maxSelectedLabels={3}  onChange={(e) => onMultiSelectChange(e, 'roleUsers')} />
                        */}
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Create;
