// laravel/v3/frontend/src/app/module/admin/view/security/model-permission-user/edit/model-permission-user-edit-admin.component.ts
import {Component, OnInit, Input} from '@angular/core';


import {AbstractEditController} from 'src/app/zynerator/controller/AbstractEditController';

import {ModelPermissionUserAdminService} from 'src/app/controller/service/admin/security/ModelPermissionUserAdmin.service';
import {ModelPermissionUserDto} from 'src/app/controller/model/security/ModelPermissionUser.model';
import {ModelPermissionUserCriteria} from 'src/app/controller/criteria/security/ModelPermissionUserCriteria.model';


import {UserDto} from 'src/app/controller/model/security/User.model';
import {UserAdminService} from 'src/app/controller/service/admin/security/UserAdmin.service';
import {ModelPermissionDto} from 'src/app/controller/model/security/ModelPermission.model';
import {ModelPermissionAdminService} from 'src/app/controller/service/admin/security/ModelPermissionAdmin.service';
import {ActionPermissionDto} from 'src/app/controller/model/security/ActionPermission.model';
import {ActionPermissionAdminService} from 'src/app/controller/service/admin/security/ActionPermissionAdmin.service';

@Component({
  selector: 'app-model-permission-user-edit-admin',
  templateUrl: './model-permission-user-edit-admin.component.html'
})
export class ModelPermissionUserEditAdminComponent extends AbstractEditController<ModelPermissionUserDto, ModelPermissionUserCriteria, ModelPermissionUserAdminService>   implements OnInit {






    constructor( private modelPermissionUserService: ModelPermissionUserAdminService , private userService: UserAdminService, private modelPermissionService: ModelPermissionAdminService, private actionPermissionService: ActionPermissionAdminService) {
        super(modelPermissionUserService);
    }

    ngOnInit(): void {
        this.actionPermission = new ActionPermissionDto();
        this.actionPermissionService.findAll().subscribe((data) => this.actionPermissions = data);
        this.modelPermission = new ModelPermissionDto();
        this.modelPermissionService.findAll().subscribe((data) => this.modelPermissions = data);
        this.user = new UserDto();
        this.userService.findAll().subscribe((data) => this.users = data);
    }


    public setValidation(value: boolean){
        }
    public validateForm(): void{
        this.errorMessages = new Array<string>();
    }



   public async openCreateModelPermission(modelPermission: string) {
        const isPermistted = await this.roleService.isPermitted('ModelPermission', 'edit');
        if (isPermistted) {
             this.modelPermission = new ModelPermissionDto();
             this.createModelPermissionDialog = true;
        }else {
             this.messageService.add({
                severity: 'error', summary: 'erreur', detail: 'problème de permission'
            });
        }
    }
   public async openCreateActionPermission(actionPermission: string) {
        const isPermistted = await this.roleService.isPermitted('ActionPermission', 'edit');
        if (isPermistted) {
             this.actionPermission = new ActionPermissionDto();
             this.createActionPermissionDialog = true;
        }else {
             this.messageService.add({
                severity: 'error', summary: 'erreur', detail: 'problème de permission'
            });
        }
    }
   public async openCreateUser(user: string) {
        const isPermistted = await this.roleService.isPermitted('User', 'edit');
        if (isPermistted) {
             this.user = new UserDto();
             this.createUserDialog = true;
        }else {
             this.messageService.add({
                severity: 'error', summary: 'erreur', detail: 'problème de permission'
            });
        }
    }

   get modelPermission(): ModelPermissionDto {
       return this.modelPermissionService.item;
   }
  set modelPermission(value: ModelPermissionDto) {
        this.modelPermissionService.item = value;
   }
   get modelPermissions(): Array<ModelPermissionDto> {
        return this.modelPermissionService.items;
   }
   set modelPermissions(value: Array<ModelPermissionDto>) {
        this.modelPermissionService.items = value;
   }
   get createModelPermissionDialog(): boolean {
       return this.modelPermissionService.createDialog;
   }
  set createModelPermissionDialog(value: boolean) {
       this.modelPermissionService.createDialog= value;
   }
   get actionPermission(): ActionPermissionDto {
       return this.actionPermissionService.item;
   }
  set actionPermission(value: ActionPermissionDto) {
        this.actionPermissionService.item = value;
   }
   get actionPermissions(): Array<ActionPermissionDto> {
        return this.actionPermissionService.items;
   }
   set actionPermissions(value: Array<ActionPermissionDto>) {
        this.actionPermissionService.items = value;
   }
   get createActionPermissionDialog(): boolean {
       return this.actionPermissionService.createDialog;
   }
  set createActionPermissionDialog(value: boolean) {
       this.actionPermissionService.createDialog= value;
   }
   get user(): UserDto {
       return this.userService.item;
   }
  set user(value: UserDto) {
        this.userService.item = value;
   }
   get users(): Array<UserDto> {
        return this.userService.items;
   }
   set users(value: Array<UserDto>) {
        this.userService.items = value;
   }
   get createUserDialog(): boolean {
       return this.userService.createDialog;
   }
  set createUserDialog(value: boolean) {
       this.userService.createDialog= value;
   }



}

        <p-dialog [(visible)]="editDialog" [style]="{width: '70vw'}" header="{{'modelPermissionUser.tabPan' | translate}}" [modal]="true" styleClass="p-fluid" [maximizable]="true" [draggable]="false" [resizable]="false">
            <ng-template pTemplate="content" >
                <p-tabView>
                    <p-tabPanel header="{{'modelPermissionUser.tabPan' | translate}}">
                        <div class="grid">

                                        <div class="field align-inputswitch col-12  md:col-6">
                                            <div  class="label-inputswitch">
                                                <label for="1">{{'modelPermissionUser.value' | translate}}</label>
                                            </div>
                                            <div class="input-switch">
                                                <p-inputSwitch id="1"  [(ngModel)]="item.value"
                                                         >
                                                </p-inputSwitch>
                                                
                                            </div>
                                        </div>


                                        <div class="field col-12 md:col-6">
                                            <label for="2">{{'modelPermissionUser.subAttribute' | translate}}</label>
                                            <input class="mb-2 mr-2" type="text" pInputText  placeholder="{{'modelPermissionUser.subAttribute' | translate}}" id="2" [(ngModel)]="item.subAttribute"
                                                     />
                                            
                                        </div>



                                    <div class="field col-11 md:col-5">
                                        <label for="3">{{'modelPermissionUser.actionPermission' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="actionPermissions" [(ngModel)]="item.actionPermission" id="3" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="id" placeholder="{{'modelPermissionUser.actionPermission' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                        <div class="col-1">
                                            <label></label>
                                            <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateActionPermission('ActionPermission')" class="p-button-success one-colonne-btn-success-align"></button>
                                        </div>
                                    <div class="field col-11 md:col-5">
                                        <label for="4">{{'modelPermissionUser.modelPermission' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="modelPermissions" [(ngModel)]="item.modelPermission" id="4" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="id" placeholder="{{'modelPermissionUser.modelPermission' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                        <div class="col-1">
                                            <label></label>
                                            <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateModelPermission('ModelPermission')" class="p-button-success one-colonne-btn-success-align"></button>
                                        </div>
                                    <div class="field col-11 md:col-5">
                                        <label for="5">{{'modelPermissionUser.user' | translate}}</label>
                                        <p-dropdown  appendTo="body"  [options]="users" [(ngModel)]="item.user" id="5" [filter]="true" filterMatchMode="contains"
                                                [showClear]="true" optionLabel="id" placeholder="{{'modelPermissionUser.user' | translate}}"  >
                                        </p-dropdown>
                                        
                                    </div>
                                        <div class="col-1">
                                            <label></label>
                                            <button pButton pRipple type="button" icon="pi pi-plus" (click)="openCreateUser('User')" class="p-button-success one-colonne-btn-success-align"></button>
                                        </div>
                        </div>
                    </p-tabPanel>

                </p-tabView>
            </ng-template>

            <ng-template pTemplate="footer" >
                <div class="grid-footer">
                        <div>
                            <button pButton pRipple label="Annuler" icon="pi pi-times" class="p-button-outlined" (click)="hideEditDialog()"></button>
                        </div>
                    <div>
                        <button pButton pRipple label="Valider" icon="pi pi-check" style="margin:10px" (click)="edit()"></button>
                    </div>
                </div>
            </ng-template>

                    <app-action-permission-create-admin></app-action-permission-create-admin>
                    <app-model-permission-create-admin></app-model-permission-create-admin>
                    <app-user-create-admin></app-user-create-admin>


    </p-dialog>

// next/security/user and permission/frontend/components/admin/view/security/model-permission-user/edit/model-permission-user-edit-admin.component.tsx
import {Button} from 'primereact/button';
import {Column} from 'primereact/column';
import {Dropdown, DropdownChangeEvent} from 'primereact/dropdown';
import {TabView, TabPanel} from 'primereact/tabview';
import {Dialog} from 'primereact/dialog';
import {InputNumber, InputNumberChangeEvent} from 'primereact/inputnumber';
import {InputText} from 'primereact/inputtext';
import {classNames} from 'primereact/utils';
import { InputTextarea } from 'primereact/inputtextarea';
import React, {useEffect, useState} from 'react';
import {Calendar} from 'primereact/calendar';
import { format } from 'date-fns';
import { parse } from 'date-fns';
import { InputSwitch } from 'primereact/inputswitch';
import {MultiSelect, MultiSelectChangeEvent} from 'primereact/multiselect';


import {MessageService} from '@/utils/zynerator/service/MessageService';


import {TFunction} from "i18next";
import {Toast} from "primereact/toast";

import useEditHook from "@/utils/zyhook/useEdit.hook";


import {ModelPermissionUserAdminService} from '@/controller/service/admin/security/ModelPermissionUserAdminService.service';
import  {ModelPermissionUserDto}  from '@/controller/model/security/ModelPermissionUser.model';
import {ModelPermissionUserCriteria} from "@/controller/criteria/security/ModelPermissionUserCriteria.model";


import {UserDto} from '@/controller/model/security/User.model';
import {UserAdminService} from '@/controller/service/admin/security/UserAdminService.service';
import {ModelPermissionDto} from '@/controller/model/security/ModelPermission.model';
import {ModelPermissionAdminService} from '@/controller/service/admin/security/ModelPermissionAdminService.service';
import {ActionPermissionDto} from '@/controller/model/security/ActionPermission.model';
import {ActionPermissionAdminService} from '@/controller/service/admin/security/ActionPermissionAdminService.service';


type ModelPermissionUserEditAdminType = {
    visible: boolean,
    onClose: () => void,
    showToast: React.Ref<Toast>,
    selectedItem: ModelPermissionUserDto
    update: (item: ModelPermissionUserDto) => void,
    list: ModelPermissionUserDto[],
    service: ModelPermissionUserAdminService,
    t: TFunction
}
const Edit: React.FC<ModelPermissionUserEditAdminType> = ({visible, onClose, showToast, selectedItem, update, list, service, t}) => {


    const isFormValid = () => {
    let errorMessages = new Array<string>();
        return errorMessages.length == 0 ;
    }
    const emptyItem = new ModelPermissionUserDto();


    const {
        item,
        setItem,
        submitted,
        setSubmitted,
        activeIndex,
        setActiveIndex,
        activeTab,
        setActiveTab,
        onInputTextChange,
        onInputDateChange,
        onInputNumerChange,
        onMultiSelectChange,
        onBooleanInputChange,
        onDropdownChange,
        onTabChange,
        hideDialog,
        editItem,
        formateDate,
        parseToIsoFormat,
        adaptDate
        } = useEditHook<ModelPermissionUserDto, ModelPermissionUserCriteria>({list, selectedItem, onClose, update, showToast,service, t, isFormValid})

    const [modelPermissions, setModelPermissions] = useState<ModelPermissionDto[]>([]);
    const [actionPermissions, setActionPermissions] = useState<ActionPermissionDto[]>([]);
    const [users, setUsers] = useState<UserDto[]>([]);


    const userAdminService = new UserAdminService();
    const modelPermissionAdminService = new ModelPermissionAdminService();
    const actionPermissionAdminService = new ActionPermissionAdminService();
    useEffect(() => {
    actionPermissionAdminService.getList().then(({data}) => setActionPermissions(data)).catch(error => console.log(error));
    modelPermissionAdminService.getList().then(({data}) => setModelPermissions(data)).catch(error => console.log(error));
    userAdminService.getList().then(({data}) => setUsers(data)).catch(error => console.log(error));


        }, []);







    const itemDialogFooter = ( <>
        <Button label="Cancel" icon="pi pi-times" text onClick={hideDialog} />
        <Button label="Save" icon="pi pi-check" onClick={editItem} /> </>
    );



    return(
    <Dialog visible={visible} style={{width: '70vw'}} header={t("modelPermissionUser.tabPan")} modal className="p-fluid" footer={itemDialogFooter} onHide={hideDialog}>
        <TabView activeIndex={activeIndex} onTabChange={onTabChange}>
            <TabPanel header={t("modelPermissionUser.tabPan")}>
                <div className="formgrid grid">
                    <div className="field col-6">
                        <div  className="label-inputswitch">
                            <label htmlFor="value">{t("modelPermissionUser.value")}</label>
                            <span className="p-float-label">
                                <InputSwitch  id="value" checked={item.value} onChange={(e) => onBooleanInputChange(e, 'value')} />
                            </span>
                        </div>
                    </div>
                    <div className="field col-6">
                        <label htmlFor="subAttribute">{t("modelPermissionUser.subAttribute")}</label>
                        <InputText id="subAttribute" value={item ? item.subAttribute : ''} onChange={(e) => onInputTextChange(e, 'subAttribute')} required className={classNames({'p-invalid': submitted && !item.subAttribute})} />
                        {submitted && !item.subAttribute && <small className="p-invalid">SubAttribute is required.</small>}
                    </div>
                    <div className="field col-6">
                        <label htmlFor="actionPermission">{t("modelPermissionUser.actionPermission")}</label>
                        <Dropdown  id="actionPermissionDropdown"  value={item ? item.actionPermission : ''} options={actionPermissions} onChange={(e) => onDropdownChange(e, 'actionPermission')}   placeholder="Sélectionnez un actionPermission" filter filterPlaceholder="Rechercher un actionPermission" optionLabel="id" showClear />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="modelPermission">{t("modelPermissionUser.modelPermission")}</label>
                        <Dropdown  id="modelPermissionDropdown"  value={item ? item.modelPermission : ''} options={modelPermissions} onChange={(e) => onDropdownChange(e, 'modelPermission')}   placeholder="Sélectionnez un modelPermission" filter filterPlaceholder="Rechercher un modelPermission" optionLabel="id" showClear />
                    </div>
                    <div className="field col-6">
                        <label htmlFor="user">{t("modelPermissionUser.user")}</label>
                        <Dropdown  id="userDropdown"  value={item ? item.user : ''} options={users} onChange={(e) => onDropdownChange(e, 'user')}   placeholder="Sélectionnez un user" filter filterPlaceholder="Rechercher un user" optionLabel="id" showClear />
                    </div>
                </div>
            </TabPanel>
        </TabView>
    </Dialog>
);
};
export default Edit;
